name: ✨ Feature Request
description: Suggest a new idea for Traydee
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution

  - type: textarea
    attributes:
      label: Alternatives Considered
